defaults:
  - _self_
  # Import the SKELify-SPIN callback.
  - /pipeline/skelify-refiner@skelify

_target_: lib.modeling.callbacks.SKELifySPIN

# This configuration are for frozen backbone exp with batch_size = 24000

cfg:
  interval: 0 #每次都执行
  batch_size: 0  # when greater than `interval * dataloader's batch_size`, it's equivalent to that 取决于实际大小
  max_batches_per_round: 0  # only the latest k * batch_size items are SPINed to save time
  # better_pgt_fn: '${_pm_.inputs}/datasets/skel_training_data/spin/better_pseudo_gt.npz'
  better_pgt_fn: '${output_dir}/better_pseudo_gt.npz' #保存伪标签
  skip_warm_up_steps: 0 #不跳过（即从训练的第一个epoch就开始更新）
  update_better_pgt: True
  valid_betas_threshold: 2
