# @package _global_
defaults:
  - /pipeline: hsmr
  - /data: skel-hsmr_v1_full
  # Configurations in this file
  - _self_
  # Import callbacks. 回调配置
  - /callback/ckpt/top1-p1k@callbacks.ckpt
  - /callback/skelify-spin/i230kb1@callbacks.SKELifySPIN
  # - /callback/skelify-spin/read_only@callbacks.SKELifySPIN

# ======= Overwrite Section =======
# (Do not use as much as possible!)

pipeline:
  cfg:
    backbone: ${_hub_.models.backbones.mamba2}
    #backbone_ckpt: '${_pm_.inputs}/backbone/vitpose_backbone.pth'  初始化的预训练权重
    freeze_backbone: False

data:
  cfg:
    train:
      dataloader:
        batch_size: 32
    mocap: NULL


# ====== Main Section ======

exp_topic: 'HSMR-train-t-mamba_2'

enable_time_monitor: True

seed: NULL
ckpt_path: NULL

logger:
  interval: 1000
  interval_skelify: 10
  samples_per_record: 5

task: 'fit'
pl_trainer:
  devices: 1
  max_epochs: 10
  deterministic: false
  precision: 16